# Generated by Django 3.2.20 on 2023-08-16 06:30

import django.core.validators
from django.db import migrations, models
import eventer_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=30, validators=[django.core.validators.MinValueValidator(2)])),
                ('category', models.CharField(choices=[('Sports', 'Sports'), ('Festivals', 'Festivals'), ('Conferences', 'Conferences'), ('Performing Art', 'Performing Art'), ('Concerts', 'Concerts'), ('Theme Party', 'Theme Party'), ('Other', 'Other')], max_length=14)),
                ('description', models.TextField(blank=True, null=True)),
                ('date', models.DateField(validators=[eventer_app.web.validators.validate_date_not_in_the_past])),
                ('event_image', models.URLField()),
            ],
        ),
    ]
