# Generated by Django 3.2.20 on 2023-08-16 08:21

import django.core.validators
from django.db import migrations, models
import eventer_app.web.validators


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='first_name',
            field=models.CharField(default='', max_length=20, validators=[eventer_app.web.validators.validate_sting_contains_only_letters]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='last_name',
            field=models.CharField(default='', max_length=30, validators=[django.core.validators.MinValueValidator(4)]),
        ),
    ]
